require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe MyAppsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MyApp. As you add validations to MyApp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { title: "Mi aplicacion", javascript_origins: "http://localhost" }
  }

  let(:invalid_attributes) {
    { title: "" }
  }

  let(:my_app) {
    FactoryGirl.create(:my_app)
  }

  before :each do
    request.session[:user_id] = my_app.user.id
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      get :edit, params: {id: my_app.to_param}
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MyApp" do
        expect {
          post :create, params: {my_app: valid_attributes}
        }.to change(MyApp, :count).by(1)
      end

      it "redirects to the created my_app" do
        post :create, params: {my_app: valid_attributes}
        expect(response).to redirect_to("/")
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {my_app: invalid_attributes}
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { title: "Nuevo titulo" }
      }

      it "updates the requested my_app" do
        put :update, params: {id: my_app.to_param, my_app: new_attributes}
        my_app.reload
        expect(my_app.title).to eq("Nuevo titulo")
      end

      it "redirects to the my_app" do
        put :update, params: {id: my_app.to_param, my_app: valid_attributes}
        expect(response).to redirect_to("/")
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, params: {id: my_app.to_param, my_app: invalid_attributes}
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested my_app" do
      expect {
        delete :destroy, params: {id: my_app.to_param}
      }.to change(MyApp, :count).by(-1)
    end

    it "redirects to the my_apps list" do
      delete :destroy, params: {id: my_app.to_param}
      expect(response).to redirect_to("/")
    end
  end

end
